### PR TITLE
Feature/#3 hexa arch graph mojo

### PR DESCRIPTION
**Pull request by javathought**
simpliest migration as a mojo

### CODE REVIEW

**Comment by binout** [comment]
I make some cleaning to use java 8 lambda and extract some methods, are you ok ?

**Comment by binout** [comment]
Then i test the plugin on my personal projects and it fails ...
Do I need to add all dependencies to plugin ?? jackson, javax.servlet, ...

[ERROR] Failed to execute goal io.github.livingdocumentation:livingdoc-maven-plugin:0.2-SNAPSHOT:diagram (diagram) on project XXX: Execution diagram of goal io.github.livingdocumentation:livingdoc-maven-plugin:0.2-SNAPSHOT:diagram failed: A required class was missing while executing io.github.livingdocumentation:livingdoc-maven-plugin:0.2-SNAPSHOT:diagram: Lcom/fasterxml/jackson/databind/ObjectMapper;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.github.livingdocumentation:livingdoc-maven-plugin:0.2-SNAPSHOT

**Comment by javathought** [comment]
Your right : the test project I used had no dependency (flottio). I'll add one and search a solution.

**Comment by javathought** [comment]
I do not reproduce the bug, adding this dependencies to test project : 

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.12</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.6.1</version>
        </dependency>
```

**Comment by javathought** [comment]
Reproduced on a more complex project

**Comment by javathought** [comment]
@binout,

The bug should be fixed (it's ok on 2 projects )

**Comment by binout** [comment]
Ok, no more problem with dependencies and classpath !

But in my personal project, the graph is now empty :-(

**Comment by javathought** [comment]
I added a filter, I think I have a bug when the property is not set. I'll correct it this evening

Can you confirm setting it ?

````
<packageExcludes>
<packageExclude>anything</packageExclude>
</packageExcludes>

````

**Comment by binout** [comment]
With the previous setting, alway empty

**Comment by javathought** [comment]
Strange, can you try with commit 	`0dbe893` ?

**Comment by javathought** [comment]
I'm not able to reproduce. Can you run with -X to show parameters values of the mojo :

Only classes with package name beginning with `prefix` are shown in the diagram (no default). 
The only reason I identify for an empty graph is you code does not match prefix.

I've added a default empty list for the exclude parameter.

**Comment by javathought** [comment]
I've found the problem : goal compile must be run before.
I'll have to "force" it.

**Comment by javathought** [comment]
"Corrected" : it's now binded to the `process-classes` class. So run the phase (`mvn clean process-classes`) and the diagram is populated. If you run `mvn clean livingdoc:diagram` it will be empty. 

It's the normal behavior of maven. A goal does not trigger other ones even if they expect them for "correct" result. 

As for packaging : 
run `mvn clean package` and you the jar is "correctly" generated
run `mvn clean jar:jar` and you the jar is generated but empty (only a META-INF folder)

**Comment by binout** [comment]
Ok you can merge it on develop (can't do it from github)

**Comment by binout** [comment]
Tested with my project : it works :-)

**Pull request merged**
