### PR TITLE
Init integration tests

### PR DESCRIPTION
**Pull request by binout**
Work in progress
Resolves issue #11

### CODE REVIEW

**Comment by binout** [comment]
Add mechanism to test mojos, first example on GlossaryMojo
Ready to merge !

**Review by javathought — COMMENTED** [review]
Great plugin `maven-invoker-plugin` to run integration tests but BeanShell is unmaintained. Isn't Groovy a better solution ?

**Comment by binout** [comment]
Yes great idea, i will convert bsh to groovy

**Comment by binout** [comment]
bsh => groovy,

@javathought ok for merge ?

**Review by javathought — APPROVED** [review]
Nice. Ok for me

**Pull request merged**
